### PR TITLE
feat: inject script into multiple process

### PR DESCRIPTION
**Pull request by popomore**
```js
require('childprocess').inject(function(modulePath, args, opt) {
  args = [
    'cover',
    '--report', 'none',
    '--print', 'none',
    '--include-all-sources',
    '--include-pid',
    modulePath,
    '--'
  ].concat(args);
  modulePath = require('path').join(process.cwd(), 'node_modules/.bin/istanbul');
  return [modulePath, args, opt];
});
require('child_process').fork(nodeBin);
```

### CODE REVIEW

**Comment by popomore** [comment]
Needn't support 0.12 now.

**Comment by popomore** [comment]
It's ready. @fengmk2

**Comment by fengmk2** [comment]
+1

**Comment by fengmk2** [comment]
major change

**Comment by fengmk2** [comment]
2.0.0

**Pull request merged**
